DROP TABLE CLIENTE

CREATE TABLE CLIENTE (
	ID_Cliente INT NOT NULL,
  	Nome VARCHAR(1055) NOT NULL,
	CPF CHAR(14) NOT NULL,
  	RG CHAR(12) NOT NULL,
  	Logradouro VARCHAR(100) NOT NULL,
  	CEP CHAR(9) NOT NULL,
  	UF CHAR(2) NOT NULL,
  	Cidade VARCHAR(30) NOT NULL,
  	Telefone CHAR(16) NOT NULL,
  	E-mail VARCHAR(355) NOT NULL,
  	CNH CHAR(9) NOT NULL,
  	Renda FLOAT(10) NULL
  );